export const MLT_TAG = {
    MLT: 'mlt',
    PROFILE: 'profile',
    PRODUCER: 'producer',
    PLAYLIST: 'playlist',
    ENTRY: 'entry',
    TRACTOR: 'tractor',
    MULTITRACK: 'multitrack',
    TRACK: 'track',
    PROPERTY: 'property',
    FILTER: 'filter',
    TRANSITION: 'transition',
    CHAIN: 'chain',
};

export const ALLOWED_CHILDREN = {
    [MLT_TAG.MLT]: [MLT_TAG.PROFILE, MLT_TAG.PRODUCER, MLT_TAG.PLAYLIST, MLT_TAG.TRACTOR, MLT_TAG.CHAIN],
    [MLT_TAG.PROFILE]: [MLT_TAG.PROPERTY],
    [MLT_TAG.CHAIN]: [MLT_TAG.PROPERTY, MLT_TAG.FILTER],
    [MLT_TAG.PRODUCER]: [MLT_TAG.PROPERTY, MLT_TAG.FILTER],
    [MLT_TAG.PLAYLIST]: [MLT_TAG.ENTRY, MLT_TAG.PROPERTY],
    [MLT_TAG.TRACTOR]: [MLT_TAG.PROPERTY, MLT_TAG.MULTITRACK, MLT_TAG.FILTER, MLT_TAG.TRANSITION],
    [MLT_TAG.MULTITRACK]: [MLT_TAG.TRACK],
    [MLT_TAG.ENTRY]: [MLT_TAG.PROPERTY, MLT_TAG.FILTER, MLT_TAG.PRODUCER],
    [MLT_TAG.TRACK]: [MLT_TAG.PROPERTY, MLT_TAG.FILTER, MLT_TAG.PRODUCER],
    [MLT_TAG.FILTER]: [MLT_TAG.PROPERTY],
    [MLT_TAG.TRANSITION]: [MLT_TAG.PROPERTY],
    [MLT_TAG.PROPERTY]: ['#text']
};

export const ALLOWED_REFERENCES = {
    [MLT_TAG.ENTRY]: [MLT_TAG.PRODUCER, MLT_TAG.PLAYLIST, MLT_TAG.TRACTOR],
    [MLT_TAG.TRACK]: [MLT_TAG.PRODUCER, MLT_TAG.PLAYLIST, MLT_TAG.TRACTOR],
    [MLT_TAG.CHAIN]: [MLT_TAG.PRODUCER],
    [MLT_TAG.TRANSITION]: [MLT_TAG.TRACK] // Links via track IDs/Indices
};
